### ISSUE TITLE
Do not depent on system clock

### ISSUE THREAD

**Issue by kpp** [zugz/tox-DHTAnnouncements#4]
> Furthermore, if a user's system clock is sufficiently incorrect, the system will quietly fail. Note that Tor also requires a roughly accurate system clock, and this seems to be a somewhat common problem for users.

Even if Tor uses it it does not mean it is correct. A user may quietly fail to launch the app and they don't care why it failed, they will close the app and delete it.

**Comment by zugz** [comment]
Yes, this is an ugly feature of this system. But I don't see how to avoid 
it.

What do you think of the suggested workaround: "Clients might be advised to 
check the system clock against remote clocks, and inform the user if the 
system clock appears to be significantly wrong"?

**Comment by kurnevsky** [comment]
> inform the user if the system clock appears to be significantly wrong

They might not only inform the user but hint toxcore about correct time.

**Comment by kpp** [comment]
Yes, that would be a solution

**Comment by GrayHatter** [comment]
Why not add the clock time used to generate the responses to the response?

If the drift is more than [small int] from the clock time we want to use, then we can [do something]

**Comment by kpp** [comment]
> the responses to the response?

?

**Comment by zugz** [comment]
* Thursday, 2019-04-04 at 13:07 -0700 - Gregory Mullen <notifications@github.com>:

>Why not add the clock time used to generate the responses to the response?

I'm not sure what you mean here. But note if it's relevant that 
revealing our precise clock time publically opens us up to being tracked 
by characteristics of our system clock.

**Comment by kpp** [comment]
Still you can be tracked because of https://github.com/zugz/tox-DHTAnnouncements/issues/7. So why bother with system clock?
