### ISSUE TITLE
Keep one AnnouncementData for all friends

### ISSUE THREAD

**Issue by kpp** [zugz/tox-DHTAnnouncements#5]
https://github.com/zugz/tox-DHTAnnouncements/blob/master/DHTAnnouncements.md#store-announcement-request

> The payload is authenticated and encrypted with the announcement secret key and the recipient's DHT public key and the given nonce

If I get it right you want to store N*AnnouncementData on announce nodes where N=number of friends. This can be avoided using `crypto_sign_ed25519` to sign the data by announcement secret key and verified by announcement public key. Or any other signing mechanism.

This will allow us to keep only one record per key.

**Comment by zugz** [comment]
If I understand you correctly, this is handled by the "shared announcements"

**Comment by GrayHatter** [comment]
We don't want to sign anything we give out, because that can be used to prove which peer generated the announce.

The friend keypair shouldn't be used for anything other than generating the handshake, unless I misunderstand what you're suggesting.

**Comment by kpp** [comment]
> We don't want to sign anything we give out

Yeah that's why there is a vulnerability by design: https://blog.tox.chat/2018/04/security-vulnerability-and-new-toxcore-release/
