### ISSUE TITLE
Use CurveCP or NOISE

### ISSUE THREAD

**Issue by kpp** [zugz/tox-DHTAnnouncements#8]
Take a look at: https://tox.chat/faq.html#tox-leak-ip
> Tox makes no attempt to cloak your IP address when communicating with friends, as the whole point of a peer-to-peer network is to connect you directly to your friends.

So what's the point of hiding static PK->IP in the level of Tox protocol? Instead we can use static PK as a DHT PK so it would be easy to find a friend. If you want to hide your IP, use Tor or any other protocol to hide your IP even from friends. 

To hide the social graph we can use https://github.com/auditdrivencrypto/secure-channel/blob/master/prior-art.md#curvecp  CurveCp algo (https://curvecp.org/):

> Bob and Alice now know who they are talking to, (although they will continue to converse as Andy and Betty instead, sneaky!)

With minor issues:
> A replay attacker may confirm that a server is actually bob...
> If Bob's keys are compromised, an attacker can connect to Bob and pretend to be anyone

Or even use any suitable handshake from https://noiseprotocol.org/noise.html#identity-hiding. I believe CurveCP is NK handshake in terms of NOISE

**Comment by zugz** [comment]
* Friday, 2019-04-05 at 15:30 +0000 - Roman Proskuryakov <notifications@github.com>:

>So what's the point of hiding static PK->IP on the level of Tox 
>protocol?

The point is that we do not hide the friend relation in terms of IP 
addresses -- in particular because relays (TCP servers) and the nodes we 
use to facilitate hole punching see the IP addresses of both parties. So 
if the "static PK <-> IP" relation is not hidden, then the friend 
relation in terms of static PKs isn't hidden.

Note that Tor etc doesn't help here -- it doesn't matter whether the IP 
addresses involved are the "real" ones, only that they're the ones being 
used for the friend connections.

>CurveCp

Interesting, but I don't see that it helps with the above problem. Does 
it?

**Comment by kpp** [comment]
> but I don't see that it helps with the above problem. Does it?

Yes. Because you initiate handshake with ephemeral PK, so you hide the relations of staticPK <-> staticPK.

> The point is that we do not hide the friend relation in terms of IP addresses. ... So if the "static PK <-> IP" relation is not hidden, then the friend relation in terms of static PKs isn't hidden.

See Net Crypto docs:

```
cookie request packet
[uint8_t 24]
[Sender's DHT Public key (32 bytes)]
[Random nonce (24 bytes)]
[Encrypted message containing:
    [Sender's real public key (32 bytes)]
    [padding (32 bytes)]
    [uint64_t echo id (must be sent back untouched in cookie response)]
]

Encrypted message is encrypted with sender's DHT private key, receiver's DHT public key and the nonce.
```

Once you trick Alice to send `cookie request packet` to Mallory she can learn Alice's real PK and IP.
Is it possible to trick Alice?

**Comment by zugz** [comment]
>you initiate handshake with ephemeral PK, so you hide the relations of 
>staticPK <-> staticPK.

I don't follow you. Could you expand?

>Once you trick Alice to send `cookie request packet` to Mallory she can 
>learn Alice's real PK and IP.
>Is it possible to trick Alice?

The connection info is authenticated (using authenticated encryption for 
individual announcements and signatures for shared and invite 
announcements), so it shouldn't be possible.

**Comment by kpp** [comment]
> Could you expand?

Sure. Please take a look at https://github.com/auditdrivencrypto/secure-channel/blob/master/prior-art.md#curvecp . Ephemeral PKs stands for Andy and Betty.

>  so it shouldn't be possible.

Yeah but is it possible for Alice to initiate net crypto with a wrong peer?

**Comment by zugz** [comment]
* Friday, 2019-04-05 at 12:19 -0700 - Roman Proskuryakov <notifications@github.com>:

>https://github.com/auditdrivencrypto/secure-channel/blob/master/prior-art.md#curvecp 

Could you explain how you see this replacing what in the current 
proposal? I don't see the relevance.

>Yeah but is it possible for Alice to initiate net crypto with a wrong 
>peer?

What are you getting at?

**Comment by kpp** [comment]
> Could you explain how you see this replacing what in the current proposal?

Assuming that we don't have to hide IP<->StaticPK using CurveCP will allow us to hide StaticPK<->StaticPK relations.
